#pragma once

#include "ui_MeshSmoothingToolbarBase.h" // this file is auto-generated by Qt/CMake

enum class SmoothingMethod {
    Implicit,
    Explicit,
};

enum class AreaFormulation {
    Barycentric,  // Each face area divided equally among vertices
    MixedVoronoi, // Mixed weights according to Meyer '03, Discrete Differential-Geometry Operators for Triangulated 2-Manifolds
};

enum class LaplacianWeights {
    Uniform,
    Cotan,
};


struct SmoothingSettings {
    SmoothingMethod method;
    LaplacianWeights laplacian;
    bool preserve_volume;
    double timestep;
    std::size_t iterations;
    double feature_enhance_alpha;
};

class MeshSmoothingToolbar : public QWidget, public Ui::MeshSmoothingToolbarBase
{
    Q_OBJECT
public:
    MeshSmoothingToolbar(QWidget * parent = nullptr);
    LaplacianWeights getLaplacianType() const;
    SmoothingMethod getSmoothingMethod() const;
    SmoothingSettings getSettings() const;
    bool show_preview() const { return cb_preview->isChecked();}
signals:
    /// Settings change that does not require iteration history recomputation
    void minorSettingsChanged();
    /// Settings change that requires complete recomputation
    void majorSettingsChanged();
};
