#include "CurveSmoothingPlugin.hh"
#include <Eigen/Sparse>
#include <ObjectTypes/PolyLineCollection/PluginFunctionsPolyLineCollection.hh>
#include <ObjectTypes/PolyLineCollection/PolyLineCollectionObject.hh>
#include <ObjectTypes/PolyLineCollection/PolyLineCollection.hh>
#include <ObjectTypes/PolyLine/PolyLine.hh>
#include <ObjectTypes/PolyMesh/PolyMesh.hh>
#include <ObjectTypes/PolyMesh/PolyMesh.hh>
#include <ObjectTypes/PolyMesh/PolyMeshTypes.hh>
#include <ObjectTypes/PolyMesh/PluginFunctionsPolyMesh.hh>
#include <ObjectTypes/PolyLine/PolyLineObject.hh>
#include <ObjectTypes/PolyLine/PluginFunctionsPolyLine.hh>
#include <ObjectTypes/PolyhedralMesh/PolyhedralMesh.hh>
#include <ObjectTypes/PolyhedralMesh/PluginFunctionsPolyhedralMesh.hh>
#include <random>
#include <limits>

#include "ui_CurveSmoothingToolbarBase.h" // this file is auto-generated by Qt/CMake

#define ASSIGNMENT_04_SOLUTION 1

using Point = ACG::Vec3d;
using ACG::Vec3d;

static ACG::Vec3d polylineCenter(SimplePolyLine const& line, bool closed)
{
    std::size_t line_vertex_length = line.size();

    ACG::Vec3d summed_vertex_locations(0.);
    for (std::size_t current_vertex_idx = 0; current_vertex_idx < line_vertex_length; ++current_vertex_idx) {
        summed_vertex_locations += line[current_vertex_idx];
    }

    return summed_vertex_locations / line_vertex_length;
};

double polylineMinEdgeLength(SimplePolyLine const& line, bool is_closed)
{
    std::size_t line_size = line.size();
    if (line_size == 0) {
        return 0;
    }

    double shortest_edge_length = std::numeric_limits<double>::infinity();
    std::size_t end_idx = is_closed ? line_size + 1 : line_size;

    OpenMesh::DefaultTraitsDouble::Point previous_vertex = line[0];
    for (std::size_t current_vertex_idx = 1; current_vertex_idx < end_idx; ++current_vertex_idx) {
        OpenMesh::DefaultTraitsDouble::Point current_vertex = line[current_vertex_idx % line_size];

        double current_edge_length = (current_vertex - previous_vertex).norm();
        shortest_edge_length = std::min(shortest_edge_length, current_edge_length);

        previous_vertex = current_vertex;
    }
    
    return shortest_edge_length;
}

double polylineLength(SimplePolyLine const& line, bool is_closed)
{
    std::size_t line_size = line.size();
    if (line_size == 0) {
        return 0;
    }

    double total_length = 0.;
    OpenMesh::DefaultTraitsDouble::Point previous_vertex = line[0];
    for (std::size_t current_vertex_idx = 1; current_vertex_idx < line_size; ++current_vertex_idx) {
        OpenMesh::DefaultTraitsDouble::Point current_vertex = line[current_vertex_idx];

        double current_segment_length = (current_vertex - previous_vertex).length();
        total_length += current_segment_length;

        previous_vertex = current_vertex;
    }

    return total_length;
}

void
CurveSmoothingPlugin::
rescaleCurve(SimplePolyLine &line, bool closed, double target_length)
{
    std::size_t line_size = line.size();

    double current_length = polylineLength(line, closed);
    double scaling_factor = target_length / current_length;

    ACG::Vec3d polyline_center = polylineCenter(line, closed);
    for (std::size_t current_vertex_idx = 0; current_vertex_idx < line_size; ++current_vertex_idx) {
        ACG::Vec3d current_vertex = line[current_vertex_idx];
        line[current_vertex_idx] = scaling_factor * current_vertex - (scaling_factor - 1) * polyline_center;
    }

    assert(std::abs(polylineLength(line, closed) - target_length) < 1e-4);
}

Point compute_circumcenter(const Point& p0, const Point& p1, const Point& p2) {
    ACG::Vec3d plane_normal = (p0 - p1).cross(p2 - p1).normalized();

    // Determines the circumcenter by solving a linear system using Cramer's rule:
    //
    // I:   |circumcenter - p0| = |circumcenter - p1|
    // II:  |circumcenter - p2| = |circumcenter - p1|   (I + II: all points have equal distance to circumcenter)
    // III: plane_normal * (circumcenter - p1) = 0      (circumcenter must lie in the triangle's plane)
    //
    // Linear system follows from expanding the expressions and bringing 
    // all terms that depend on circumcenter's coordinates on the left-hand side and bringing
    // all terms that are independent of those coordinates on the right-hand side

    ACG::Matrix3x3d cramer_matrix = ACG::Matrix3x3d::fromRows(
        2 * (p0 - p1), 
        2 * (p2 - p1), 
        plane_normal);

    ACG::Vec3d cramer_vector(
        p0.sqrnorm() - p1.sqrnorm(), 
        p2.sqrnorm() - p1.sqrnorm(), 
        plane_normal.dot(p1));

    double cramer_determinant = cramer_matrix.det();
    if (std::abs(cramer_determinant) < 1e-4) {
        return p1;
    }

    double circumcenter_x = ACG::Matrix3x3d::fromColumns(
        cramer_vector, 
        cramer_matrix.getCol(1), 
        cramer_matrix.getCol(2)
    ).det() / cramer_determinant;

    double circumcenter_y = ACG::Matrix3x3d::fromColumns(
        cramer_matrix.getCol(0), 
        cramer_vector,
        cramer_matrix.getCol(2)
    ).det() / cramer_determinant;

    double circumcenter_z = ACG::Matrix3x3d::fromColumns(
        cramer_matrix.getCol(0), 
        cramer_matrix.getCol(1),
        cramer_vector 
    ).det() / cramer_determinant;

    return Point(circumcenter_x, circumcenter_y, circumcenter_z);
}

void
CurveSmoothingPlugin::
smoothLaplacian(SimplePolyLine const& input, SimplePolyLine &output, bool closed, double eps)
{
    assert (&input != &output);
    
    int line_size = input.size();
    int end_idx = line_size + 1;

    if (!closed) {
        end_idx = line_size - 1;
        output[0] = input[0];
        output[line_size - 1] = input[line_size - 1];
    }
    
    for (int current_vertex_idx = 1; current_vertex_idx < end_idx; ++current_vertex_idx) {
        OpenMesh::DefaultTraitsDouble::Point previous_neighbor = input[current_vertex_idx - 1];
        OpenMesh::DefaultTraitsDouble::Point current_vertex = input[current_vertex_idx % line_size];
        OpenMesh::DefaultTraitsDouble::Point next_neighbor = input[(current_vertex_idx + 1) % line_size];

        auto neighbor_midpoint = 0.5 * (previous_neighbor + next_neighbor);
        auto smoothened_point = (1 - eps) * current_vertex + eps * neighbor_midpoint;

        output[current_vertex_idx % line_size] = smoothened_point;
    }
}

void
CurveSmoothingPlugin::
smoothCurvatureFlow(SimplePolyLine const& input, SimplePolyLine &output, bool closed, double eps)
{
    const int input_size = input.size();
    double global_min_edge_length = polylineMinEdgeLength(input, closed);
    double global_dt = (global_min_edge_length * global_min_edge_length);
    //double global_dt = 1.0; // Q: What happens if you use this? Can you choose a good step size?

    int line_size = input.size();
    int end_idx = line_size + 1;

    if (!closed) {
        end_idx = line_size - 1;
        output[0] = input[0];
        output[line_size - 1] = input[line_size - 1];
    }

    for (int current_vertex_idx = 1; current_vertex_idx < end_idx; ++current_vertex_idx) {
        OpenMesh::DefaultTraitsDouble::Point previous_neighbor = input[current_vertex_idx - 1];
        OpenMesh::DefaultTraitsDouble::Point current_vertex = input[current_vertex_idx % line_size];
        OpenMesh::DefaultTraitsDouble::Point next_neighbor = input[(current_vertex_idx + 1) % line_size];

        auto circumcenter = compute_circumcenter(previous_neighbor, current_vertex, next_neighbor);

        double squared_radius = (current_vertex - circumcenter).sqrnorm();

        double scaling_factor = eps * global_dt * (1 / squared_radius);
        output[current_vertex_idx % line_size] = (1 - scaling_factor) * current_vertex + scaling_factor * circumcenter;
    }
}


class CurveSmoothingToolbar : public QWidget, public Ui::CurveSmoothingToolbarBase
{
    public:
    CurveSmoothingToolbar(QWidget * parent = nullptr)
        : QWidget(parent)
    {
        setupUi(this);
    }
};

void CurveSmoothingPlugin::initializePlugin()
{
    tool_ = new CurveSmoothingToolbar();

    connect(tool_->cb_import_ovm, &QPushButton::clicked, this, &CurveSmoothingPlugin::slotImportOVM);

    // (re-) create curve when curve generation settings are changed or button is pressed:
    connect(tool_->btn_random_curve, &QPushButton::clicked, this, &CurveSmoothingPlugin::slotCreateRandomCurve);
    connect(tool_->sb_npoints, &QSpinBox::valueChanged, this, &CurveSmoothingPlugin::slotCreateRandomCurve); 
    connect(tool_->cb_closed, &QCheckBox::toggled, this, &CurveSmoothingPlugin::slotCreateRandomCurve);
    connect(tool_->cb_curve2d, &QCheckBox::toggled, this, &CurveSmoothingPlugin::slotCreateRandomCurve);
    connect(tool_->sb_seed, &QSpinBox::valueChanged, this, &CurveSmoothingPlugin::slotCreateRandomCurve);

    // (re-)compute smoothing if any smoothing parameter changes:
    connect(tool_->sb_steps, &QSpinBox::valueChanged, this, &CurveSmoothingPlugin::slotSmooth);
    connect(tool_->rb_laplacian, &QRadioButton::toggled, this, &CurveSmoothingPlugin::slotSmooth);
    connect(tool_->rb_osc_circle, &QRadioButton::toggled, this, &CurveSmoothingPlugin::slotSmooth);
    connect(tool_->dsb_eps, &QDoubleSpinBox::valueChanged, this, &CurveSmoothingPlugin::slotSmooth);
    connect(tool_->cb_rescale, &QCheckBox::toggled, this, &CurveSmoothingPlugin::slotSmooth);
    connect(tool_->cb_vis_intermediate, &QCheckBox::toggled, this, &CurveSmoothingPlugin::slotSmooth);

    emit addToolbox( tr("GP Ex04: Curve Smoothing") , tool_ );
}

PolyLineObject& CurveSmoothingPlugin::getOrCreateCurveObject(int &id, QString const& name, ACG::Vec4f const &color)
{
    if (auto *plo = PluginFunctions::polyLineObject(id)) {
        return *plo;
    } else {
        emit addEmptyObject(DATA_POLY_LINE, id);
        plo = PluginFunctions::polyLineObject(id);
        plo->setName(name);
        plo->materialNode()->set_line_width(5);
        plo->materialNode()->set_point_size(10);
        plo->materialNode()->set_color(color);
        return *plo;
    }
}

PolyLineObject& CurveSmoothingPlugin::getOrCreateInputCurveObject()
{
    auto &obj = getOrCreateCurveObject(input_curve_obj_id_,
            "Input curve", ACG::Vec4f(.5f, .4f, 1.f, 1.f));
    obj.target(true);
    return obj;
}

PolyhedralMeshObject& CurveSmoothingPlugin::getOrCreateOutputMeshObject()
{
    if (auto *pmo = PluginFunctions::polyhedralMeshObject(output_mesh_obj_id_)) {
        return *pmo;
    } else {
        emit addEmptyObject(DATA_POLYHEDRAL_MESH, output_mesh_obj_id_);
        pmo = PluginFunctions::polyhedralMeshObject(output_mesh_obj_id_);
        pmo->setName("Smoothed curve");
        pmo->materialNode()->set_line_width(5);
        pmo->materialNode()->set_point_size(10);
        pmo->materialNode()->set_color(ACG::Vec4f(.9f, .6f, .2f, 1.f));
        pmo->setObjectDrawMode(
                  ACG::SceneGraph::DrawModes::getDrawMode("Edges (wireframe)")
                | ACG::SceneGraph::DrawModes::getDrawMode("Vertices")
                , true);
        return *pmo;
    }
}

PolyhedralMeshObject& CurveSmoothingPlugin::getOrCreateVisualizationMeshObject()
{
    if (auto *pmo = PluginFunctions::polyhedralMeshObject(vis_mesh_obj_id_)) {
        pmo->show(); // this may have been hidden before
        return *pmo;
    } else {
        emit addEmptyObject(DATA_POLYHEDRAL_MESH, vis_mesh_obj_id_);
        pmo = PluginFunctions::polyhedralMeshObject(vis_mesh_obj_id_);
        pmo->setName("Smoothing visualisation");
        pmo->materialNode()->set_line_width(1);
        pmo->materialNode()->set_point_size(1);
        pmo->materialNode()->set_color(ACG::Vec4f{0.3, 0.3, 0.6, 1.0});
        pmo->materialNode()->set_specular_color(ACG::Vec4f{0.5, 0.5, 0.5, 1.0});
        pmo->setObjectDrawMode(
                  ACG::SceneGraph::DrawModes::getDrawMode("Edges (wireframe)")
                | ACG::SceneGraph::DrawModes::getDrawMode("Faces (flat shaded)")
                | ACG::SceneGraph::DrawModes::getDrawMode("Vertices")
                , true);
        return *pmo;
    }
}

void CurveSmoothingPlugin::slotImportOVM()
{
    // Note: You may ignore this function, it's not really related to the point of the exercise.

    for (BaseObjectData * obj: PluginFunctions::objects(
                PluginFunctions::TARGET_OBJECTS,
                DATA_POLYHEDRAL_MESH))
    {
        PolyhedralMeshObject *pmo = PluginFunctions::polyhedralMeshObject(obj);
        PolyhedralMesh const &mesh = *pmo->mesh();
        auto visited = mesh.create_private_vertex_property("visited", false);

        auto line = PolyLine{false};
        int count = 0;
        // simple but inefficient hack to ensure we start enumerating each polyline at
        // one of its end vertices: sort vertices by their valence.
        // This works as long as the input is a collection of polylines,
        // and may or may not do something sensible if we have vertices with valence >=3.
        std::vector<std::pair<int, OpenVolumeMesh::VH>> valence_vh;
        valence_vh.reserve(mesh.n_vertices());
        for (const auto vh: mesh.vertices()) {
            valence_vh.emplace_back(mesh.valence(vh), vh);
        }
        std::sort(valence_vh.begin(), valence_vh.end());

        // Run depth-first search to turn OVM mesh into collection of polylines
        for (const auto& [valence, first_vh] : valence_vh) {
            line.set_closed(false); // we will close it if necessary
            line.clear();
            if (visited[first_vh]) continue;
            auto cur_vh = first_vh;
            auto last_vh = OpenVolumeMesh::VH(-1);

            bool keep_going = true;
            do {
                line.add_point(mesh.vertex(cur_vh));
                visited[cur_vh] = true;
                keep_going = false;
                for (const auto next_vh: mesh.vertex_vertices(cur_vh)) {
                    if (next_vh == last_vh) continue;
                    if (next_vh == first_vh) {
                        line.set_closed(true);
                        break;
                    }
                    if (visited[next_vh]) continue;
                    last_vh = cur_vh;
                    cur_vh = next_vh;
                    keep_going = true;
                    break;
                }
            } while(keep_going);

            if ( (!line.is_closed() && line.n_vertices() < 2)
                || (line.is_closed() && line.n_vertices() < 3))
            {
                continue;
            }

            int obj_id = BaseObject::NOOBJECT;
            auto& curve_obj = getOrCreateCurveObject(obj_id,
                    QString("Imported curve %1").arg(++count),
                    ACG::Vec4f(.5f, .4f, 1.f, 1.f));
            curve_obj.target(true);
            *curve_obj.line() = line;
        }
    }
}

void CurveSmoothingPlugin::slotCreateRandomCurve()
{
    // Note: You may ignore this function, it's not super exciting.
    //       feel free to substitute your own random (or less random)
    //       curve generation. Let us know if you come up with something nicer than this.

    auto &input_curve_obj = getOrCreateInputCurveObject();
    auto &polyline = *input_curve_obj.line();
    polyline.clear();
    polyline.set_closed(tool_->cb_closed->isChecked());

    const bool two_d = tool_->cb_curve2d->isChecked();
    const int n_points = tool_->sb_npoints->value();

    int seed = tool_->sb_seed->value();
    std::default_random_engine gen(seed);
    std::normal_distribution<double> noise_dist(0., 1. / (n_points+3));
    std::uniform_real_distribution<double> phase_dist(0., 2*M_PI);

    constexpr int n_octaves = 10;
    std::array<double, n_octaves> phases;
    for (int i = 0; i < n_octaves; ++i) {
        phases[i] = phase_dist(gen);
    }
    for (int k = 0; k < n_points; ++k) {
        const double phi = 2 * M_PI * (k + .5) / n_points;
        Point p{0.};
        double freq = 1.;
        for (int i = 1; i <= n_octaves; ++i) {
            auto w = 1. / (i*i);
            auto phase = phases[i-1];
            p[0] += w * sin(freq * phi + phase);
            p[1] += w * cos(freq * phi + phase);
            if (!two_d) { p[2] += w * sin(2 * freq * phi + phase); }
            freq *= 2;
        }
        if (0) {
            p[0] += noise_dist(gen);
            p[1] += noise_dist(gen);
            if (!two_d) { p[2] += noise_dist(gen); }
        }
        polyline.add_point(p);
    }
    slotSmooth();
    emit updatedObject(input_curve_obj.id(), UPDATE_ALL);
}


void CurveSmoothingPlugin::smoothCurve(
        PolyLine input, PolyhedralMesh *out_mesh, PolyhedralMesh *vis_mesh)
{
    const int n_steps = tool_->sb_steps->value();
    CurveSmoothingMethod method;
    if (tool_->rb_laplacian->isChecked()) {
        method = CurveSmoothingMethod::UniformLaplacian;
    } else {
        assert(tool_->rb_osc_circle->isChecked());
        method = CurveSmoothingMethod::OsculatingCircle;
    }
    const double eps = tool_->dsb_eps->value();

    /// Copy a given polyline into a OVM mesh, return vector of edge handles
    auto add_polyline_to_ovm = [](PolyhedralMesh &mesh, PolyLine const& line)
        -> std::vector<OpenVolumeMesh::EdgeHandle>
    {
        std::vector<OpenVolumeMesh::EdgeHandle> edges; edges.reserve(line.n_edges());
        int first_new_vh = mesh.n_vertices();
        auto last_vh = OpenVolumeMesh::VertexHandle(-1);
        for (auto &p: line.points()) {
            auto vh = mesh.add_vertex(p);
            if (last_vh.is_valid()) {
                auto eh = mesh.add_edge(last_vh, vh);
                edges.push_back(eh);
            }
            last_vh = vh;
        }
        if (line.is_closed()) {
            auto eh = mesh.add_edge(last_vh, OpenVolumeMesh::VertexHandle(first_new_vh));
            edges.push_back(eh);
        }
        return edges;
    };

    /// helper for visualizing smoothing trajectories
    auto add_quad_strip_to_ovm = [] (
        PolyhedralMesh &mesh,
        std::vector<OpenVolumeMesh::EdgeHandle> const &last,
        std::vector<OpenVolumeMesh::EdgeHandle> const &cur)
    {
        assert(cur.size() == last.size());
        int n = last.size();
        for (int i = 0; i < n; ++i) {
            mesh.add_face({
                mesh.edge(last[i]).from_vertex(),
                mesh.edge(last[i]).to_vertex(),
                mesh.edge(cur[i]).to_vertex(),
                mesh.edge(cur[i]).from_vertex()
                });
        }
    };
    std::vector<OpenVolumeMesh::EdgeHandle> ovm_edges;

    PolyLine output;
    output.set_closed(input.is_closed());
    output.resize(input.n_vertices());
    if (vis_mesh) {
        ovm_edges = add_polyline_to_ovm(*vis_mesh, input);
    }
    double totalLength = polylineLength(input.points(), input.is_closed());
    for (int i = 0; i < n_steps; ++i) {
        switch (method) {
            case CurveSmoothingMethod::UniformLaplacian:
                smoothLaplacian(input.points(), output.points(), input.is_closed(), eps);
                break;
            case CurveSmoothingMethod::OsculatingCircle:
                smoothCurvatureFlow(input.points(), output.points(), input.is_closed(), eps);
                break;
        }

        if (tool_->cb_rescale->isChecked()) {
            rescaleCurve(output.points(), input.is_closed(), totalLength);
        }

        if (vis_mesh) {
            auto edges = add_polyline_to_ovm(*vis_mesh, output);
            if (!ovm_edges.empty()) {
                add_quad_strip_to_ovm(*vis_mesh, ovm_edges, edges);
            }
            ovm_edges = edges;
        }
        // Use output as input for the next iteration:
        std::swap(input, output);
    }
    if (n_steps > 0) {
        // The last iteration has swapped input and output, so "input" contains the final result:
        add_polyline_to_ovm(*out_mesh, input);
    }
}

void CurveSmoothingPlugin::slotSmooth()
{

    PolyhedralMesh *vis_mesh = nullptr;
    if (tool_->cb_vis_intermediate->isChecked()) {
        auto &pmo = getOrCreateVisualizationMeshObject();
        vis_mesh = pmo.mesh();
        vis_mesh->clear(false);
    } else {
        auto *pmo = PluginFunctions::polyhedralMeshObject(vis_mesh_obj_id_);
        if (pmo) pmo->hide();
    }

    auto &output_obj = getOrCreateOutputMeshObject();
    output_obj.mesh()->clear(false);


    for (BaseObjectData * obj: PluginFunctions::objects(
                PluginFunctions::TARGET_OBJECTS,
                DATA_POLY_LINE))
    {
        auto *input = PluginFunctions::polyLineObject(obj->id())->line();
        if (input->n_vertices() < 2) { return; }
        smoothCurve(*input, output_obj.mesh(), vis_mesh);
    }

    emit updatedObject(output_obj.id(), UPDATE_ALL);
    if (vis_mesh) {
        emit updatedObject(vis_mesh_obj_id_, UPDATE_ALL);
    }

}

