#include "RemeshingPlugin.hh"
#include "Remeshing.hh"

#include "ui_RemeshingToolbarBase.h" // this file is auto-generated by Qt/CMake

class RemeshingToolbar : public QWidget, public Ui::RemeshingToolbarBase
{
    public:
    RemeshingToolbar(QWidget * parent = nullptr)
        : QWidget(parent)
    {
        setupUi(this);
    }

    RemeshingConfig getConfig() const
    {
        RemeshingConfig config;
        config.type = cb_adaptive->isChecked() ? RemeshingType::Adaptive : RemeshingType::Uniform;
        config.target_length_ratio = target_length_ratio_dsb->value();
        return config;
    };
};


template <typename Fn>
void for_each_target_trimesh(Fn&& fn)
{
    for (BaseObjectData * obj: PluginFunctions::objects(
                PluginFunctions::TARGET_OBJECTS,
                DATA_TRIANGLE_MESH))
    {
        TriMeshObject *tmo = PluginFunctions::triMeshObject(obj);
        if (!tmo) continue;
        fn(*tmo);
    }
}

namespace PodNames {
    static const char* const remesher = "Plugin-Ex09-Remeshing/Remesher";
}

Remeshing& RemeshingPlugin::get_or_create_remesh_pod(TriMeshObject& object)
{
    if (auto *pod = dynamic_cast<Remeshing*>(object.objectData(PodNames::remesher))) {
        return *pod;
    }
    auto *pod = new Remeshing(*object.mesh(), tool_->getConfig());
    object.setObjectData(PodNames::remesher, pod);
    return *pod;
}

template <typename Fn>
void RemeshingPlugin::for_each_target_trimesh_remesh(Fn&& fn)
{
    for_each_target_trimesh([&](TriMeshObject &tmo) {
        auto &remesher = get_or_create_remesh_pod(tmo);
        fn(remesher);
        tmo.meshNode()->drawMode(ACG::SceneGraph::DrawModes::WIREFRAME | ACG::SceneGraph::DrawModes::SOLID_SMOOTH_SHADED);
        tmo.mesh()->update_normals();
        emit updatedObject(tmo.id(), UPDATE_ALL);
    });
}

void RemeshingPlugin::initializePlugin()
{
    tool_ = new RemeshingToolbar();
    connect(tool_->pb_remesh, &QPushButton::clicked, this, &RemeshingPlugin::slot_remesh);
    connect(tool_->pb_smooth, &QPushButton::clicked, this, &RemeshingPlugin::slot_smooth);
    connect(tool_->pb_flip, &QPushButton::clicked, this, &RemeshingPlugin::slot_flip);
    connect(tool_->pb_split, &QPushButton::clicked, this, &RemeshingPlugin::slot_split);
    connect(tool_->pb_collapse, &QPushButton::clicked, this, &RemeshingPlugin::slot_collapse);
    connect(tool_->pb_init, &QPushButton::clicked, this, &RemeshingPlugin::slot_init);

    emit addToolbox( tr("GP Ex09: Remeshing") , tool_ );

}
void RemeshingPlugin::slot_remesh() {
    auto n_iters = tool_->sb_iters->value();

    for_each_target_trimesh_remesh([&](Remeshing &rem) {
        for (int i = 0; i < n_iters; ++i) {
            bool changed = rem.remesh();
            if (!changed) {
                emit log (LOGINFO, "Remeshing finished early after " + QString::number(i) + " iterations.");
                return;
            }
        }
    });
}

void RemeshingPlugin::slot_init() {
    auto config = tool_->getConfig();
    for_each_target_trimesh_remesh([&](Remeshing &rem) {
        rem.init(config);
    });
}
void RemeshingPlugin::slot_smooth() {
    auto n_iters = tool_->sb_iters->value();

    for_each_target_trimesh_remesh([&](Remeshing &rem) {
        rem.tangential_relaxation();
    });
}

void RemeshingPlugin::slot_split() {
    for_each_target_trimesh_remesh([&](Remeshing &rem) {
        rem.split_long_edges();
    });
}
void RemeshingPlugin::slot_collapse() {
    for_each_target_trimesh_remesh([&](Remeshing &rem) {
        rem.collapse_short_edges();
    });
}
void RemeshingPlugin::slot_flip() {
    for_each_target_trimesh_remesh([&](Remeshing &rem) {
        rem.equalize_valences();
    });
}
