#include "GPHelloEigenPlugin.hh"
#include <Eigen/Sparse>

#include "ui_GPHelloEigenToolbarBase.h" // this file is auto-generated by Qt/CMake

class GPHelloEigenToolbar : public QWidget, public Ui::GPHelloEigenToolbarBase
{
    public:
    GPHelloEigenToolbar(QWidget * parent = nullptr)
        : QWidget(parent)
    {
        setupUi(this);
    }
};

void GPHelloEigenPlugin::initializePlugin()
{
    tool_ = new GPHelloEigenToolbar();
    connect(tool_->hello_eigen, &QPushButton::clicked, this, &GPHelloEigenPlugin::slotHelloEigen);
    emit addToolbox( tr("GP Ex01: Hello Eigen") , tool_ );
}

void GPHelloEigenPlugin::slotHelloEigen()
{
    //     [ 2  3  0  0  0 ]       [  8]
    //     [ 3  0  4  0  6 ]       [ 45]
    //     [ 0 -1 -3 -2  0 ] * x = [ -3]
    //     [ 0  0  1  0  0 ]       [  3]
    //     [ 0  2  4  0  1 ]       [ 19]
    std::vector<Eigen::Triplet<double>> entriesA;
    entriesA.push_back({0, 0, 2});
    entriesA.push_back({0, 1, 3});
    entriesA.push_back({1, 0, 3});
    entriesA.push_back({1, 2, 4});
    entriesA.push_back({1, 4, 6});
    entriesA.push_back({2, 1, -1});
    entriesA.push_back({2, 2, -3});
    entriesA.push_back({2, 3, -2});
    entriesA.push_back({3, 2, 1});
    entriesA.push_back({4, 1, 2});
    entriesA.push_back({4, 2, 4});
    entriesA.push_back({4, 4, 1});

    auto A = Eigen::SparseMatrix<double>(5, 5);
    A.setFromTriplets(entriesA.begin(), entriesA.end());

    auto b = Eigen::VectorXd(5);
    b << 8, 45, -3, 3, 19;

    Eigen::SparseLU decompositionA(A);
    Eigen::VectorXd x = decompositionA.solve(b);

    std::cout<<"Linear system Ax = b. \nA is:\n"<<A<<std::endl;
    std::cout<<"b is:\n"<<b<<std::endl;
    std::cout<<"x is:\n"<<x<<std::endl;
    double err = (A*x - b).lpNorm<2>();
    if (err < 1e-8) {
        emit log(LOGINFO, "Solution verified, error = " + QString::number(err));
    } else {
        emit log(LOGERR, "Error: wrong solution, error = " + QString::number(err));
    }
}

